      - name: Setup Bitcoin Vanity Tools
        shell: powershell
        run: |
          $toolsDir = "C:\BitcoinVanity"
          New-Item -ItemType Directory -Path $toolsDir -Force | Out-Null

          # ... (download code remains the same) ...

          # Create README using regular string instead of here-string
          $readmeLines = @(
            "Bitcoin Vanity Address Generator (v1.19)",
            "",
            "File: VanitySearch.exe is ready in this folder.",
            "",
            "Quick examples:",
            "  VanitySearch.exe 1Ejaz         # Search for addresses starting with 1Ejaz",
            "  VanitySearch.exe -t 0 1Love    # Use all CPU threads",
            "  VanitySearch.exe -gpu 1My      # Try GPU mode (not available on GitHub)",
            "",
            "More options:",
            "  VanitySearch.exe --help"
          )
          $readmeContent = $readmeLines -join "`r`n"
          Set-Content -Path "$toolsDir\README.txt" -Value $readmeContent -Encoding UTF8

          # Create batch file using regular string
          $batLines = @(
            "@echo off",
            "title Bitcoin Vanity Tools",
            "echo Bitcoin Vanity Address Generator",
            "echo ================================",
            "echo.",
            "echo Tool: VanitySearch.exe",
            "echo Location: %~dp0",
            "echo.",
            "echo Examples:",
            "echo   VanitySearch.exe 1Ejaz",
            "echo   VanitySearch.exe -t 0 1Love",
            "echo.",
            "echo Check README.txt for more details",
            "echo.",
            "pause"
          )
          $batContent = $batLines -join "`r`n"
          Set-Content -Path "$toolsDir\start.bat" -Value $batContent -Encoding ASCII

          Write-Host "Tools folder created: $toolsDir"
